server:
  port: 8085

spring:
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  datasource:
    url: jdbc:postgresql://localhost:5432/shop_notifications
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres


jwt:
  secretcode: really_big_secret_code_trust_me_i_always_right
  issuer: notification-service

services:
  user:
    uri: http://localhost:8081