server:
  port: 8084

spring:
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  datasource:
    url: jdbc:postgresql://localhost:5432/shop_order
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres


jwt:
  secretcode: really_big_secret_code_trust_me_i_always_right
  issuer: order-service

orders:
  commission: 0.05

services:
  organization:
    uri: http://localhost:8083
  product:
    uri: http://localhost:8082
  user:
    uri: http://localhost:8081