server:
  port: 8082

spring:
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  datasource:
    url: jdbc:postgresql://localhost:5432/shop_products
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

logging:
  level:
    org.springframework.security: DEBUG

jwt-secretcode: really_big_secret_code_trust_me_i_always_right
jwt-issuer: user-service/shop/effective-mobile